export const MEME_WORDS = [
  "栓 Q",
  "问薪吾溃",
  "泰裤辣",
  "蚌埠住了",
  "班味",
  "草台班子",
  "丝瓜汤",
  "蒜鸟蒜鸟",
  "老登",
  "哈基米",
  "显眼包",
  "遥遥领先",
  "我真的会谢",
  "精神状态",
  "纯爱战士",
  "i人e人",
  "嘎嘎乱杀",
  "脆皮大学生",
  "公主请上车",
  "命运的齿轮",
];

export const GROUPS = [
  {
    id: "group-internet-slang",
    name: "互联网黑话",
    core: ["meme-shuanq", "meme-bangbuzhule", "meme-taikula"],
    hidden: "meme-xianyanb",
  },
  {
    id: "group-work-life",
    name: "打工人之殇",
    core: ["meme-wenxinwukui", "meme-banwei", "meme-caotaibanzi"],
    hidden: "meme-cuipidxs",
  },
];

export const TIERS = [
  { id: "easy", name: "简单", desc: "入门级梗词，节奏宽松" },
  { id: "normal", name: "普通", desc: "稍有挑战，干扰增多" },
  { id: "hard", name: "困难", desc: "时间紧迫，假目标密集" },
  { id: "hell", name: "地狱", desc: "极限挑战，真假难辨" },
];

export const LEVELS = [
  {
    id: "meme-shuanq",
    char: "栓 Q",
    tier: "easy",
    fragments: ["栓", "Q"],
    polluted: "\u201c感谢\u201d语义被异化为无语和敷衍",
    origin: "源于英文 thank you 的音译失真，原本是表达感谢。",
    distorted: "如今常表示无语、不满或敷衍，并不是真的感谢。",
    examples: ["这个蛋糕甜到齁，栓 Q 了家人们。", "花 300 块拍写真翻车，栓 Q。"],
    difficulty: { targets: 2, particles: 36, fakeRate: 0.35, freezeMs: 5000, timeMs: 28000, snapPx: 52 },
    theme: { id: "silk-amber", a: "#fbbf24", b: "#22d3ee", bgA: "rgba(251,191,36,0.16)", bgB: "rgba(34,211,238,0.10)", fx: "silk" },
  },
  {
    id: "meme-wenxinwukui",
    char: "问薪吾溃",
    tier: "normal",
    fragments: ["问薪", "吾溃"],
    polluted: "\u201c问心无愧\u201d被改写为职场薪资焦虑梗",
    origin: "来自成语\u201c问心无愧\u201d，本意是自省后心中坦然。",
    distorted: "被改写成\u201c被问薪水就崩溃\u201d，用于打工人收入焦虑自嘲。",
    examples: ["HR 问我期望薪资，我直接问薪吾溃。", "每次发工资都问薪吾溃。"],
    difficulty: { targets: 2, particles: 40, fakeRate: 0.36, freezeMs: 5000, timeMs: 27000, snapPx: 50 },
    theme: { id: "ink", a: "#94a3b8", b: "#22d3ee", bgA: "rgba(148,163,184,0.12)", bgB: "rgba(34,211,238,0.10)", fx: "ink" },
  },
  {
    id: "meme-taikula",
    char: "泰裤辣",
    tier: "normal",
    fragments: ["泰", "裤", "辣"],
    polluted: "\u201c太酷啦\u201d谐音梗逐渐变成反讽",
    origin: "谐音自\u201c太酷啦\u201d，原本是夸人很酷、很厉害。",
    distorted: "常用于反讽尴尬装酷或油腻发言。",
    examples: ["在图书馆外放音乐还说自己泰裤辣。", "这发言泰裤辣了（反讽）。"],
    difficulty: { targets: 3, particles: 42, fakeRate: 0.37, freezeMs: 5000, timeMs: 29000, snapPx: 48 },
    theme: { id: "crimson", a: "#fb7185", b: "#22d3ee", bgA: "rgba(251,113,133,0.14)", bgB: "rgba(34,211,238,0.10)", fx: "blink" },
  },
  {
    id: "meme-bangbuzhule",
    char: "蚌埠住了",
    tier: "easy",
    fragments: ["蚌埠", "住了"],
    polluted: "\u201c绷不住了\u201d谐音泛化为万能情绪词",
    origin: "源于\u201c绷不住了\u201d的谐音说法，原本指情绪快失控。",
    distorted: "被泛化为任何强烈情绪的统一表达，边界变得模糊。",
    examples: ["看电影结尾我蚌埠住了。", "查分那一刻真的蚌埠住了。"],
    difficulty: { targets: 2, particles: 38, fakeRate: 0.35, freezeMs: 5000, timeMs: 26000, snapPx: 50 },
    theme: { id: "rose", a: "#fb7185", b: "#fbbf24", bgA: "rgba(251,113,133,0.16)", bgB: "rgba(251,191,36,0.10)", fx: "petal" },
  },
  {
    id: "meme-banwei",
    char: "班味",
    tier: "easy",
    fragments: ["班", "味"],
    polluted: "职场状态被压缩成标签化表达",
    origin: "原是\u201c上班状态的气息\u201d组合词，描述职场疲惫感。",
    distorted: "演变成对职场倦怠的一键贴标签表达。",
    examples: ["周一一进地铁就有班味。", "今天状态不对，班味太重了。"],
    difficulty: { targets: 2, particles: 40, fakeRate: 0.38, freezeMs: 5000, timeMs: 25000, snapPx: 48 },
    theme: { id: "mist", a: "#94a3b8", b: "#38bdf8", bgA: "rgba(148,163,184,0.14)", bgB: "rgba(56,189,248,0.10)", fx: "mist" },
  },
  {
    id: "meme-caotaibanzi",
    char: "草台班子",
    tier: "hard",
    fragments: ["草台", "班子"],
    polluted: "传统戏曲术语被泛化为\u201c世界不专业\u201d调侃",
    origin: "原指民间临时戏班，是历史语境下的中性称呼。",
    distorted: "被扩展为\u201c看起来正规其实很草率\u201d的全网吐槽语。",
    examples: ["方案改八版还回第一版，草台班子。", "世界是个巨大的草台班子。"],
    difficulty: { targets: 2, particles: 44, fakeRate: 0.40, freezeMs: 5000, timeMs: 24000, snapPx: 46 },
    theme: { id: "sand", a: "#f59e0b", b: "#22d3ee", bgA: "rgba(245,158,11,0.16)", bgB: "rgba(34,211,238,0.08)", fx: "sand" },
  },
  {
    id: "meme-siguatang",
    char: "丝瓜汤",
    tier: "normal",
    fragments: ["丝瓜", "汤"],
    polluted: "家常菜语义被挪为代际沟通反制梗",
    origin: "原是以丝瓜为主材的日常汤品，强调饮食语境。",
    distorted: "演变为反击\u201c为你好\u201d式说教的挡箭牌句式。",
    examples: ["你这么凶，喝点丝瓜汤吧。", "被强行说教时我只想回一句丝瓜汤。"],
    difficulty: { targets: 2, particles: 40, fakeRate: 0.37, freezeMs: 5000, timeMs: 25000, snapPx: 48 },
    theme: { id: "sprout", a: "#34d399", b: "#22d3ee", bgA: "rgba(52,211,153,0.16)", bgB: "rgba(34,211,238,0.10)", fx: "ripple" },
  },
  {
    id: "meme-suanniaosuanniao",
    char: "蒜鸟蒜鸟",
    tier: "normal",
    fragments: ["蒜鸟", "蒜鸟"],
    polluted: "方言\u201c算了算了\u201d谐音后成为佛系挡箭牌",
    origin: "来自武汉方言\u201c算了算了\u201d的谐音表达。",
    distorted: "泛化为终止尴尬、结束沟通的万能口头禅。",
    examples: ["地铁社死了，蒜鸟蒜鸟。", "今天不纠结了，蒜鸟蒜鸟。"],
    difficulty: { targets: 2, particles: 42, fakeRate: 0.39, freezeMs: 5000, timeMs: 26000, snapPx: 46 },
    theme: { id: "wave", a: "#38bdf8", b: "#a78bfa", bgA: "rgba(56,189,248,0.14)", bgB: "rgba(167,139,250,0.10)", fx: "wave" },
  },
  {
    id: "meme-laodeng",
    char: "老登",
    tier: "easy",
    fragments: ["老", "登"],
    polluted: "东北方言词义由贬到戏谑再到亲昵化",
    origin: "源于东北方言，原本多带\u201c为老不尊\u201d的贬义。",
    distorted: "如今常被年轻人用作对中老年男性的戏谑或亲昵称呼。",
    examples: ["我家老登今天给我买了奶茶。", "这老登跳舞还挺带劲。"],
    difficulty: { targets: 2, particles: 38, fakeRate: 0.35, freezeMs: 5000, timeMs: 25000, snapPx: 50 },
    theme: { id: "autumn", a: "#fbbf24", b: "#f97316", bgA: "rgba(251,191,36,0.14)", bgB: "rgba(249,115,22,0.10)", fx: "leaf" },
  },
  {
    id: "meme-hajimi",
    char: "哈基米",
    tier: "normal",
    fragments: ["哈", "基", "米"],
    polluted: "二次元空耳词脱离原语境后泛化为\u201c可爱\u201d标签",
    origin: "来自日语\u201c蜂蜜\u201d的空耳，最初是二次元语境中的特定梗。",
    distorted: "破圈后泛化为\u201c可爱小东西\u201d的通用叫法。",
    examples: ["这只小猫好哈基米。", "这个玩偶太哈基米了。"],
    difficulty: { targets: 3, particles: 46, fakeRate: 0.40, freezeMs: 5000, timeMs: 29000, snapPx: 44 },
    theme: { id: "bloom", a: "#fbbf24", b: "#a78bfa", bgA: "rgba(251,191,36,0.14)", bgB: "rgba(167,139,250,0.10)", fx: "bloom" },
  },
  // ===== 新增关卡 =====
  {
    id: "meme-xianyanb",
    char: "显眼包",
    tier: "hell",
    fragments: ["显", "眼", "包"],
    polluted: "\u201c引人注目\u201d变成社交场合的戏谑标签",
    origin: "原指外观显眼的包裹或物品，或形容特别突出的人。",
    distorted: "变成形容在公共场合做出令人注目行为的人，半褒半贬。",
    examples: ["军训场上他穿粉色鞋，妥妥的显眼包。", "博物馆里最大的显眼包就是那个cos古人的。"],
    hidden: true,
    difficulty: { targets: 3, particles: 48, fakeRate: 0.42, freezeMs: 4000, timeMs: 26000, snapPx: 44 },
    theme: { id: "flare", a: "#f59e0b", b: "#ec4899", bgA: "rgba(245,158,11,0.16)", bgB: "rgba(236,72,153,0.10)", fx: "flare" },
  },
  {
    id: "meme-yaoyaolingxian",
    char: "遥遥领先",
    tier: "hard",
    fragments: ["遥遥", "领先"],
    polluted: "科技发布会用语被解构为万能调侃句式",
    origin: "本指在竞争中大幅度超前，常用于体育、学业等正式语境。",
    distorted: "因某手机品牌发布会频繁使用，成为对自夸行为的调侃模板。",
    examples: ["今天食堂排队我第一个，遥遥领先。", "考试倒数第一，也是遥遥领先。"],
    difficulty: { targets: 2, particles: 44, fakeRate: 0.40, freezeMs: 4500, timeMs: 25000, snapPx: 46 },
    theme: { id: "prism", a: "#a78bfa", b: "#22d3ee", bgA: "rgba(167,139,250,0.14)", bgB: "rgba(34,211,238,0.10)", fx: "prism" },
  },
  {
    id: "meme-wozhendehx",
    char: "我真的会谢",
    tier: "hell",
    fragments: ["我", "真的", "会谢"],
    polluted: "\u201c感谢\u201d语义被反转为无奈与崩溃",
    origin: "表面是\u201c我真的会感谢\u201d，实际上表达极度无奈和崩溃。",
    distorted: "原本正面的感谢语被反讽化，成为表达\u201c受不了了\u201d的情绪出口。",
    examples: ["论文查重80%，我真的会谢。", "快递寄到隔壁城市了，我真的会谢。"],
    difficulty: { targets: 3, particles: 50, fakeRate: 0.42, freezeMs: 4000, timeMs: 28000, snapPx: 42 },
    theme: { id: "aurora", a: "#34d399", b: "#0ea5e9", bgA: "rgba(52,211,153,0.14)", bgB: "rgba(14,165,233,0.10)", fx: "aurora" },
  },
  {
    id: "meme-jingshenzhuangtai",
    char: "精神状态",
    tier: "hard",
    fragments: ["精神", "状态"],
    polluted: "心理健康词汇被消解为情绪展演工具",
    origin: "原指一个人的心理与精神健康状况，属医学/心理学词汇。",
    distorted: "成为\u201c发疯文学\u201d的代名词，用于展示夸张的情绪状态博取关注。",
    examples: ["期末周我的精神状态就像这只猫。", "看看我的精神状态，已经很好了（配发疯图）。"],
    difficulty: { targets: 2, particles: 42, fakeRate: 0.38, freezeMs: 5000, timeMs: 24000, snapPx: 48 },
    theme: { id: "glitch", a: "#ec4899", b: "#8b5cf6", bgA: "rgba(236,72,153,0.14)", bgB: "rgba(139,92,246,0.10)", fx: "blink" },
  },
  {
    id: "meme-chunaizhanshi",
    char: "纯爱战士",
    tier: "hard",
    fragments: ["纯爱", "战士"],
    polluted: "爱情观标签化：纯爱成了非黑即白的站队旗帜",
    origin: "源于ACG文化，指支持纯洁、专一爱情故事的受众。",
    distorted: "泛化成网络论战工具，凡不符合\u201c纯爱\u201d标准的角色关系都被攻击。",
    examples: ["这部剧居然NTR了，纯爱战士们出击！", "作为纯爱战士我无法接受这个展开。"],
    difficulty: { targets: 2, particles: 44, fakeRate: 0.40, freezeMs: 4500, timeMs: 26000, snapPx: 46 },
    theme: { id: "petal", a: "#fb7185", b: "#f472b6", bgA: "rgba(251,113,133,0.14)", bgB: "rgba(244,114,182,0.10)", fx: "petal" },
  },
  {
    id: "meme-iren-eren",
    char: "i人e人",
    tier: "easy",
    fragments: ["i人", "e人"],
    polluted: "MBTI性格分类被简化为社交二元标签",
    origin: "源于MBTI性格测试中的内向(I)/外向(E)维度，是多维度性格评估的一部分。",
    distorted: "被极度简化为\u201c社恐\u201dvs\u201c社牛\u201d的二元标签，忽略了性格的复杂性。",
    examples: ["聚会上全是e人，我一个i人瑟瑟发抖。", "我e人属性爆发了，一口气加了三个群。"],
    difficulty: { targets: 2, particles: 40, fakeRate: 0.36, freezeMs: 5000, timeMs: 24000, snapPx: 50 },
    theme: { id: "grid", a: "#6366f1", b: "#22d3ee", bgA: "rgba(99,102,241,0.14)", bgB: "rgba(34,211,238,0.10)", fx: "grid" },
  },
  {
    id: "meme-gagaluansha",
    char: "嘎嘎乱杀",
    tier: "hard",
    fragments: ["嘎嘎", "乱杀"],
    polluted: "游戏暴力用语被泛化为日常炫耀词汇",
    origin: "原为电竞/游戏社区用语，形容在游戏中压倒性碾压对手。",
    distorted: "泛化到日常生活中，任何稍有优势的场景都用\u201c乱杀\u201d形容。",
    examples: ["数学考试嘎嘎乱杀，全班最高。", "新买的显卡跑分嘎嘎乱杀。"],
    difficulty: { targets: 2, particles: 46, fakeRate: 0.42, freezeMs: 4000, timeMs: 25000, snapPx: 44 },
    theme: { id: "heat", a: "#ef4444", b: "#f97316", bgA: "rgba(239,68,68,0.14)", bgB: "rgba(249,115,22,0.10)", fx: "heat" },
  },
  {
    id: "meme-cuipidxs",
    char: "脆皮大学生",
    tier: "hell",
    fragments: ["脆皮", "大学生"],
    polluted: "大学生群体的健康问题被解构为自嘲狂欢",
    origin: "指身体脆弱、容易受伤生病的大学生群体，反映真实的健康焦虑。",
    distorted: "自嘲式标签化让严肃的健康问题变成段子素材，消解了正视问题的可能。",
    examples: ["打个喷嚏骨折了，不愧是脆皮大学生。", "脆皮大学生日常：走路崴脚、喝水呛到。"],
    hidden: true,
    difficulty: { targets: 2, particles: 48, fakeRate: 0.44, freezeMs: 3500, timeMs: 24000, snapPx: 42 },
    theme: { id: "mist-alt", a: "#94a3b8", b: "#f59e0b", bgA: "rgba(148,163,184,0.14)", bgB: "rgba(245,158,11,0.10)", fx: "mist" },
  },
  {
    id: "meme-gongzhuqsc",
    char: "公主请上车",
    tier: "hell",
    fragments: ["公主", "请上车"],
    polluted: "宠溺称呼被商业化为流量密码",
    origin: "原为恋人间的亲昵用语，带有浪漫和宠爱的私密感。",
    distorted: "被短视频博主批量使用，成为吸引女性用户点击的营销话术。",
    examples: ["打车软���弹窗：公主请上车。", "外卖备注：公主的餐请轻放。"],
    difficulty: { targets: 2, particles: 44, fakeRate: 0.40, freezeMs: 4500, timeMs: 26000, snapPx: 46 },
    theme: { id: "silk-rose", a: "#f472b6", b: "#fbbf24", bgA: "rgba(244,114,182,0.14)", bgB: "rgba(251,191,36,0.10)", fx: "silk" },
  },
  {
    id: "meme-mingyundechilun",
    char: "命运的齿轮",
    tier: "hell",
    fragments: ["命运的", "齿轮"],
    polluted: "宿命叙事被消费为\u201c逆袭爽文\u201d开头模板",
    origin: "文学表达，形容命运中关键的转折时刻，带有庄重和宿命感。",
    distorted: "成为短视频万能开头\u201c从这一刻起，命运的齿轮开始转动\u201d，多为凡尔赛。",
    examples: ["高考填志愿那天，命运的齿轮开始转动。", "我买了一杯咖啡，命运的齿轮开始转动。"],
    difficulty: { targets: 2, particles: 50, fakeRate: 0.44, freezeMs: 4000, timeMs: 28000, snapPx: 42 },
    theme: { id: "prism-dark", a: "#8b5cf6", b: "#06b6d4", bgA: "rgba(139,92,246,0.14)", bgB: "rgba(6,182,212,0.10)", fx: "prism" },
  },
];

export const LEVEL_INDEX = Object.fromEntries(LEVELS.map((l, i) => [l.id, i]));
